### ISSUE TITLE
Problem with tpope/fugitive & MBE

### ISSUE THREAD

**Issue by finack** [fholgado/minibufexpl.vim#17]
First, thanks for the awesome work. Love MBE. Currently running off of development branch which fixed the issue with two buffers with the same name. Running into some compatibility problems between MBE and Fugitive.

1) If I go into a git repo and run fugitive's :Gstatus, I get the change buffer and all is happy. When I run 'D' diff on a change, I get the two vertical windows with vimdiff but in the fugitive git version, syntax highlighting is not working. It changes to one color.

2) If I have a couple of other buffers open and I fire up Gstatus and hit diff, the diff windows now show up about the Gstatus window but belowe the MiniBufExplorer window and is just 1 line high. I don't think syntax highlighting is working either.

Now to be fair, this may be an issue with fugitive, but if I disable MBE, I can't find similar issues with fugitive.

**Comment by fholgado** [comment]
Hey Peter,

Sorry for the delayed response. You are correct that this is a bug with MBE and not Fugitive. I am in the process of reverting back to an previous version of MBE that does not exhibit this behavior. I will keep you posted once this is fixed. Thanks for the kind words!

**Comment by rweng** [comment]
+1, seems to happen with current version (July 06, 201), too

**Comment by toupeira** [comment]
Just wanted to add that the old version 6.3.2 from vim.org has the same problem.

**Comment by skip-** [comment]
Still same problem. Versions: VIM 7.3.2, minibufexpl 6.4.1, fugitive 1.2, git 1.7.7.4
Anyone have an idea to fix this?

**Comment by toupeira** [comment]
@skip-, it seems to work fine here now, try minibufexpl 6.4.3 from the [development branch](https://github.com/fholgado/minibufexpl.vim/tree/development).

@fholgado: maybe it's time to merge that branch? ;-) I've been working with it for the past few months and haven't encountered any problems.

**Comment by fholgado** [comment]
I'm actually seeing some errors when I try to run a diff. It looks like an error being caused from MBE temporarily focusing on it's buffer to update the view... http://f.fhl.gd/EYrf

Are you guys seeing this?

**Comment by toupeira** [comment]
@fholgado: actually I'd like to retract my previous comment about it working fine, I think I confused `:Gdiff` with pressing `D` in `:Gstatus` ;-) I don't get the error message though, but the diff is between the first file buffer and the MBE buffer, instead of between the two file buffers.

What I did:
- open Vim from inside a Git repository
- run `:Gstatus`, which opens the status output in a new window
- move to the first modified file
- press `D`, which opens two new file buffers and activates MBE
- the MBE buffer and the first file buffer have `diff` set, while the second file buffer doesn't

This is with the latest commit d92c8b01248d612444829001b3e081629d37a1aa from the master branch (and again, I seem to have confused something with my previous comment about the old development branch... ;-)

**Comment by skip-** [comment]
Glad it's not my particular setup :). Any thoughts on how to fix this?

**Comment by maciakl** [comment]
I have a similar problem. Quick workaround I found was to add this to .vimrc: 

```
 let g:miniBufExplorerMoreThanOne=3
```

This prevents MBE from showing up when there are only two buffers open, which makes Gdiff work correctly. Ideally I would love to see a solution that would let me to drop that number to two.

**Comment by skip-** [comment]
I'll give that a try while this get's fixed. Thanks for the suggestion.

**Comment by weynhamz** [comment]
Hey, guys, the problem for this issue is that the MBE is fired up while entering a diff split window and the window movement history gets messed up by MBE, it should be fixed in techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048, please give it a try and let me know.

I am closing this issue, becuase it should be fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and soon will be avalible in @fholgado's repo in the next 6.5 release.

**Comment by weynhamz** [comment]
Related #3

**Comment by onilton** [comment]
@techlivezheng I'm using your fork, but I still got issues with vim-fugitive and MBE (Gdiff window is just 1 line height). 

Should I open another issue?
