### ISSUE TITLE
Feature: Make CTab & CSTab "cycle" through *all* buffers in MRU-fashion

### ISSUE THREAD

**Issue by fpauser** [fholgado/minibufexpl.vim#20]
It would be great if we could "cycle" through _all_ buffers according to their last "use" (MRU). Just like "^Tab", but while holding "Ctrl" down and pressing Tab (again and again or holding it down) it should go to the "next-most-recent-used" buffer and so on (switching not just between the last two "mru" buffers).

I found the "miniBufExplSortBy" option but what I am looking for is another "MRU"-Option which just changes the CTab/CSTab-behavior, not the visualisation of buffers. Maybe a new option called "miniBufExplCTabSwitchBufsSortBy"?

**Comment by weynhamz** [comment]
Hey, I introduced two new commands ':MBEbf' and ':MBEbb' in commit techlivezheng/vim-plugin-minibufexpl@b7d2ad5  to switch buffer forward or backward in the buffer entering history, aka cycling buffer in a MRU fashion. This functionality has been merged into [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) in commit techlivezheng/vim-plugin-minibufexpl@a4e9ce9.

Unfortunately, the key-bingings for switching betwen windows and buffers have been removed from MBE in commit techlivezheng/vim-plugin-minibufexpl@417e952, because these bindings should be up to the user to configure in their own vimrc file, see the doc for how to do that.

**Comment by weynhamz** [comment]
I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5.
