### ISSUE TITLE
:cd generates a new minibufexpl window

### ISSUE THREAD

**Issue by sontek** [fholgado/minibufexpl.vim#31]
If I'm working in vim and I want to change my working directory to the current file I'll do :cd %:p:h<CR> but then when I open up a new file it regenerates the minibufexpl window, so then I have 2 of them.

**Comment by sillykelvin** [comment]
yes, when I use :e . on specific files, I have this problem too.

**Comment by oryband** [comment]
+1

[Check this one](http://vim.1045645.n5.nabble.com/minibufexpl-and-autochdir-setting-leads-to-multiple-mini-buffers-td5711001.html)

**Comment by weynhamz** [comment]
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

I believe this issue has been fixed in my [develop branch](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) after some refactorings, please give it a try and let me know if it works.

**Comment by weynhamz** [comment]
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.
