### ISSUE TITLE
Conflict with NERDTree

### ISSUE THREAD

**Issue by noscript** [fholgado/minibufexpl.vim#44]
Previously if I split the view to many windows and open some file from NERDTree, the file was opened in the last active window, but now on NERDTree opens files always in the most top-left window. Downgrading minibufexpl to 6.3.2 from http://www.vim.org/scripts/script.php?script_id=159 fixes the problem.

**Comment by chrisnicola** [comment]
Having the same problem

**Comment by chrisnicola** [comment]
Using tag 6.4.3 fixes this behaviour so it must have been introduced recently. If I get some time I'll run git bisect and try to find the exact commit.

Update: Nevermind, for some reason it worked for a bit and now it isn't again.

**Comment by rjha** [comment]
It looks like that opening NERDTree makes the MiniBufExplorer window invisible. However if you open multiple files and then again do :MiniBufExplorer then the buffer explorer window is visible again. Sequence of steps 
1) Open gVim
2) :MiniBufExplorer
3) :NERDTree 
Buffer explorer becomes invisible
4) Open 2-3 files using NERDTree window 
5) :MiniBufExplorer
The buffer explorer window is visible again
I am using gVim 7.3 (latest on Debian wheezy) + latest version of script

**Comment by noscript** [comment]
Found the real problem, minibufexpl wasn't aware of NERDTree. There is a fix:

``` diff
--- a/plugin/minibufexpl.vim
+++ b/plugin/minibufexpl.vim
@@ -1333 +1333 @@
-  if (bufname('%') == '-MiniBufExplorer-' || bufname('%') == '[fuf]' || bufname('%') == '')
+  if (bufname('%') == '-MiniBufExplorer-' || bufname('%') == '[fuf]' || bufname('%') =~# 'NERD_tree_\d' || bufname('%') == '')
```

**Comment by weynhamz** [comment]
The original @sergey-vlasov's problem is that 'AutoUpdate()', which will temparorily switch to MBE window, is triggerd on 'BufEnter' evet while entering the NERDTree window. When a file is opened in NERDTree window, it will get the previous window to see if it is usable, at this point it is the MBE window which is not, so MBE will then use the first usable window found. That's why NERDTree always opens the file at top left window.

@rjha's problem is a little different, by calling `:MiniBufExplorer` immediately after start the vim, an empty MBE window will be start, then the following `:NERDTree` command will trigger 'AutoUpdate()` on BufEnter event while entering the NERDTree window, becasue at this point these is no eligible buffers, the MBE window gets closed again.

@sergey-vlasov's fix would work for both cases, it prevent 'AutoUpdate()' from being run in NERDTree window. After commits techlivezheng/vim-plugin-minibufexpl@c06f82d and techlivezheng/vim-plugin-minibufexpl@9d41f96, 'AutoUpdate()' will not run inside any plugin windown including NERDTree window, but this is not what caused the problem.

@sergey-vlasov's problem should be fixed in commits techlivezheng/vim-plugin-minibufexpl@3add236 and techlivezheng/vim-plugin-minibufexpl@4155048, which will make sure window switching history not be interfered by MBE any more.

@rjha's problem should be fixed by techlivezheng/vim-plugin-minibufexpl@8ac7f45, which will ignore the eligible buffers checking if MBE was opened manually.

I am closing this issue, becuase it should be fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and soon will be avalible in @fholgado's repo in the next 6.5 release.

**Comment by shepherdwind** [comment]
@fholgado seem to have no plan to release the new version, May be I should just use @techlivezhen 's branch.

**Comment by weynhamz** [comment]
Related #3
