### ISSUE TITLE
Tags get messed up

### ISSUE THREAD

**Issue by linduxed** [fholgado/minibufexpl.vim#47]
I don't know since what version this is happening, but while `:help` works as intended, with a command like `:help minibufexpl.txt` showing the help page for this plugin, the command `:tab help minibufexpl.txt` results in the following:

```
E433: No tags file
E426: tag not found: minibufexpl.txt@en
```

After these two errors, an empty tab is opened. This applies to all help pages.

**Comment by bruno-** [comment]
Yep - this is happening for me too.. very nasty, and I have to remove the MBE

**Comment by weynhamz** [comment]
Hey, I have encountered this problems several times too while developing the minibufexpl. After some changes, this problem has gone, but I am not sure which commit fixes it and I can not reproduce it even at the orginal @fholgado's master, I think it might have something to do with the configuration of the MBE, can any of you post your MBE's configuration here?

Anyway, this issue should be fixed in the [develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop), please give it a try and let me know.

By the way, a new version 6.5 will soon be released to @fholgado's repo with a bunch of fixes and improvements.

**Comment by weynhamz** [comment]
Closing this issue, it should be fixed in the develop branch by commit c06f82d, feel free to reopen it.
