### ISSUE TITLE
Conflict with Vundle on Windows

### ISSUE THREAD

**Issue by quasarj** [fholgado/minibufexpl.vim#51]
Hey there!

So.. MBE is setting "shellslash" when used on Windows. It looks like this is to make the code work that removes directory names for two files in the same directory. However.. setting shellslash on Windows is not a good idea. It causes shellquote() to use single quotes instead of double quotes, which breaks everything on Windows.

In my case, I ran into this while using Vundle. I imagine the same thing would happen with Pathogen, though I haven't tried it. When Vundle attempts to install a new Bundle with git, the command fails because the destination path is single-quoted. Commenting out the line in MBE that sets shellslash fixes the issue, though of course it causes buffers to have their full path even when they are all in the same directory.

**Comment by weynhamz** [comment]
Hey, @quasarj, I am currently maintaining ths plugin, and I do not have any Windows machine to test if this has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop), `set shellslash` should be unnecessary now but I have not remove it yet, please remove that line and give it a try, if nothing is affected, please let me know so I can remove it from the plugin.

**Comment by quasarj** [comment]
I finally got a chance to try this out, and it looks like it's working fine on windows with set shellslash removed. However, it now appears to not display the full path regardless of the location of the files. I'm not sure if that was intentional or not.

Also it is breaking Command-T in a weird way - in a fresh instance of Vim, if I have not yet caused MBE to display itself (say, by opening two buffers), trying to use Command-T results in the error
NoMethodError: undefined method 'match' for nil:NilClass

But if MBE has already been displayed it works fine. Anyway, not sure if this is a real issue or what, just thought I'd point it out.

**Comment by weynhamz** [comment]
Sounds good.

MBE should not display the full path of a buffer, it was a bug in previous versions on Windows.

It indeed breaks the Comand-T, thanks for mentioning it, I am looking into it.

**Comment by weynhamz** [comment]
I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.

By the way, the Command-T problem should have been fixed too, please take a look.
