### ISSUE TITLE
Setting miniBufExplorerMoreThanOne to 0 doesn't work anymore

### ISSUE THREAD

**Issue by ghost** [fholgado/minibufexpl.vim#54]
`let miniBufExplorerMoreThanOne = 0` still works for numbers greater than 0, but setting it to 0 doesn't cause minibufexpl to open even if there are no open buffers, despite what is said in the documentation.

Was still working in version 6.4.3.

**Comment by weynhamz** [comment]
Hey, guys

I have continued the developement of MBE for a while, a bunch of PRs have been merged into the develop branch of my fork of MBE at techlivezheng/vim-plugin-minibufexpl. 

In vim, There is always at least one open buffer even it is an empty buffer with no name. I believe this issue has been fixed since techlivezheng/vim-plugin-minibufexpl@8fad45b in my [develop branch](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop).

Please give it a try and let me know if it works.

**Comment by weynhamz** [comment]
Hey, I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.
