### ISSUE TITLE
Add an option to stop changing updatetime, it is set too low for easytags

### ISSUE THREAD

**Issue by linduxed** [fholgado/minibufexpl.vim#59]
I'm not sure if this is something that should be brought up as in issue with this plugin, but I'll mention it anyway.

The [easytags plugin](https://github.com/xolox/vim-easytags) has got a couple of lines that detects too low values of updatetime and complains loudly about it.

Currently minibufexpl does `setlocal updatetime=300` which it considers too low (due to it having to update the tags that often). I'm therefore wondering if the updatetime really needs to be that low or if there's a way to make easytags not update that fast in the minibufexpl windows (in which case this probably becomes an issue for that tracker).

**Comment by weynhamz** [comment]
I tried restoring the value of `updatetime` to the default, but that makes MBE take a noticeable delay to relect the changes of the file which is a bit unacceptble. Is it possible to patch the easytags plugin to suppress the warnings if it does not affect its functionality? If this is not a option, due to I am not using easytags, could you give it a try to see what value is appropriate for both easytags and minibufexpl?

**Comment by linduxed** [comment]
IIRC, easytags repeatedly updates the tags database/file, with the interval being governed by `updatetime`. This value can't be lowered too much, since this shouldn't be updated as often as 300 ms.  
So no, supressing the warnings isn't a solution in this case, since they're displayed for a valid reason.

As for a value both can agree on, it's hard for me to say. I don't how extensive the regular reads/writes of easytags are, so I found it to be best to just go with the default value, that is 4000.

Sure, this causes noticeable lag in MBE, but I figured that constant I/O is a bigger issue than some interface lag.

Maybe @xolox has an idea on what would be appropriate.

**Comment by weynhamz** [comment]
Right, may be I can add an option to restore the updatetime to the default value if it is needed.

**Comment by weynhamz** [comment]
If `&ut` has been set to a different value other than the default, or the 'g:miniBufExplSetUT' option is false, minBufExpl will not set `&ut` any more.

I am closing this issue, because I believe it has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) and will soon be avaliable in @fholgado's repo in the coming relase 6.5. If the problem still remains, feel free to reopen it.
