### ISSUE TITLE
minibufexpl keeps omni complete from working

### ISSUE THREAD

**Issue by fspeech** [fholgado/minibufexpl.vim#62]
I had a problem with omni completion not working. It turned out that the minibufexpl was interfering with omni completion. Here is how I found out:

Normal keyword completion works. Omni complete does not work for any language, not just Python. omnifunc is set correctly. After I C-X C-O, nothing happens. I do ":py print globals()" and it is clear that the pythoncomplete was not loaded. I can ":call pythoncomplete#Complete(1, '')" and see it get loaded. To me this rules out it being a Vim issue. It seems something is interfering with keymapping or otherwise intercept the omni completion request. So I start to disable my plugins one by one. It turns out the culprit in my case is "minibufexpl".

I am just going to disable it for now so I can use auto completion.

**Comment by weynhamz** [comment]
Hey, @fspeech, I am currently maintaining ths project, and I am not using Omni, and I do not quite understand what you mean, but from what you are saying, there is a big chance that your issue has been fixed in [the develop branch of my fork](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop), please give it a try and let me know if it still happens.

**Comment by weynhamz** [comment]
Related to #59.

It is because MBE previously set the value of 'updatetime' to 300ms which is too low, after pressing 'C-x' before 'C-o', MBE's 'AutoUpdate()' function has already intercepted it. I believe commits c99ea42 and 87543bc in develop branch have fixed this issue. You can also adjust the 'updatetime' setting yourself, MBE will respect it now.

I am closing this issue, feel free to reopen it.
