### ISSUE TITLE
Minibufexplorer breaks filetype detection

### ISSUE THREAD

**Issue by rix0rrr** [fholgado/minibufexpl.vim#71]
Hi,

I'm using minibufexpl.vim using Pathogen.

I've had the problem that using the plugin breaks filetype detection. I've been able to narrow it down to the following line:

```
call <SID>CycleBuffer(1)
```

Inside <SID>AutoUpdate(). I think a piece of code there is interfering with the autocmds that do filetype detection.

Anyway, commenting out this line seems to work for me without any ill effects. Though you'd like you know, maybe there's a structural problem in there that needs work.

**Comment by weynhamz** [comment]
Hey, the development has been moved to https://github.com/techlivezheng/vim-plugin-minibufexpl, please try the develop [branch](https://github.com/techlivezheng/vim-plugin-minibufexpl/tree/develop) to see if you still have the problem.

**Comment by rix0rrr** [comment]
That one works, thanks! Is it possible to make it more clear on this GitHub project which version is the "official" one?

**Comment by weynhamz** [comment]
On Tue, Jan 15, 2013 at 01:25:14AM -0800, Rico Huijbers wrote:

> That one works, thanks! Is it possible to make it more clear on this GitHub project which version is the "official" one?
> I am planning to release a new version to this repo after I clean up all
> the currently opened issues.

So in long term, this repo still serves as the "official" one, because many
users hard-coded it into their vimrc file and I do not want to bother them
to change it. Only development takes place in my own repo, those who can
not bear with the nasty bugs any more should use my develop branch for now,
and change back after the new version is released if they want.

**Comment by weynhamz** [comment]
I figured it out today that this issue is the main cause of the issue #24. With filetype detection broken, of course the syntax highlighting would not work properly. 

Anyway, commit cea185b removed `call <SID>CycleBuffer(1)` from the `AutoUpdate()` function which should fix this problem. 

At the end, I suspect that the reason why filetype detection is broken is because `CycleBuffer()` is trying to load a file buffer into the MBE's previous window in an autocmd, in which by default the autocmd nesting is disabled, but filetype detection is relying on `FileType` event which of couse would not in this case to be triggered. This means applying 'nested' onto our autocmds should also fix this issue, but that requires very carefully tuned autocmd configuration which  is more tricky.
