### ISSUE TITLE
buffer number is wrong

### ISSUE THREAD

**Issue by twmht** [fholgado/minibufexpl.vim#76]
This is an obvious problem

I just open two files, each one is located in one buffer

Here is my screenshot

![ _001](https://f.cloud.github.com/assets/1567200/263700/2c24c8e8-8d78-11e2-98b2-25b3b68fb7c5.png)

It is obvious that buffer number 1 is for .vimrc and number 2 is for test.sql

I want to switch to the number 2 buffer so that I use :bn 2 in normal mode; However, it is useless.

I use :bn 3 and It works!!( to switch buffer number 2 from buffer number 1)

It seems that buffer number 2 is buffer number 3.

How come this happened?

There is another obvious problem

![ _002](https://f.cloud.github.com/assets/1567200/263792/d9af136c-8d7b-11e2-9830-bdb1f1447400.png)

I open libreary.sql in the new buffer

As you can see, MiniBufExploer skipped number 3 and label it as number 4

I do not know wheather this is a bug or not.

Many thanks for considering my request:)

**Comment by pahindman** [comment]
The :bn command doesn't do what you think it does.  Here are the [docs](http://vimdoc.sourceforge.net/htmldoc/windows.html#:bn).  In this case, ":bn 2" doesn't mean go to buffer number 2.  It means go to the buffer that is two buffers after this one.  It wraps around, so since you only have two buffers, you simply end up where you started.  ":bn 3" goes one step further, which puts you on the next buffer.  Try opening lots of buffers and doing ":bn 2" over and over to see how it behaves.

If you want to go to a buffer of a particular number, use the [:b](http://vimdoc.sourceforge.net/htmldoc/windows.html#:b) command, as in ":b 2"

Buffer number 3 is probably used for the MiniBufExplorer display buffer itself, which it created after you opened the second buffer.  I doubt it is a bug.

**Comment by twmht** [comment]
Thanks for your help and contribute to this project:)
